require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc', 'method_call']

Metrics/AbcSize:
  Max: 30

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Max: 160
