require:
  - rubocop-rails
  - rubocop-rake
  - rubocop-rspec

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.0
  TargetRubyVersion: 3.1

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
