# Omakase Ruby styling for Rails
inherit_gem: { rubocop-rails-omakase: rubocop.yml }

require:
  - rubocop-rake
  - rubocop-rspec
  - rubocop-capybara
  - rubocop-factory_bot
  - rubocop-graphql

AllCops:
  NewCops: enable
  TargetRailsVersion: 7.2
  TargetRubyVersion: 3.1
  Exclude:
    - cdk/**/*

Style/StringLiterals:
  EnforcedStyle: single_quotes

Layout/SpaceInsideArrayLiteralBrackets:
  EnforcedStyle: no_space

Style/Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false

Metrics/BlockLength:
  CountAsOne: ['array', 'heredoc', 'method_call']

Metrics/AbcSize:
  Enabled: false

Metrics/CyclomaticComplexity:
  Enabled: false

Metrics/MethodLength:
  Max: 20

Rails/I18nLocaleTexts:
  Enabled: false

Layout/LineLength:
  Max: 160
