# ==============================================================
# Docker compose file for local development environment
# - starts a MySQL server with no root pw
# - mounts persistent volumes for DB data and Rails bundler cache
# - mounts current working dir into the app so code changes you make
#   locally are reflected in the container
# ==============================================================

version: "3"

services:
  app:
    build: .
      - '3000:3000'
    environment:
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_ACCESS_KEY: ${AWS_SECRET_ACCESS_KEY}
      AWS_SESSION_TOKEN: ${AWS_SESSION_TOKEN}
    volumes:
      - .:/app
      - ./vendor/bundle:/bundler

  proxy:
    image: fsouza/docker-ssl-proxy
    ports:
      - '3000:443'
    environment:
      DOMAIN: 'nabu'
      TARGET_PORT: 3000
      TARGET_HOST: app

  db:
    image: mysql:8
    ports:
      - '3306:3306'
    volumes:
      - db-data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'

  search:
    image: solr:8
    ports:
      - '8983:8983'
    volumes:
      - ./solr:/var/solr/data
    restart:
      unless-stopped

volumes:
  db-data:
  search-data:
