production:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: 172.19.0.1
    port: 8983
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: 172.19.0.1
    port: 8983
    log_level: WARNING
    path: /solr/test

staging:
  solr:
    hostname: localhost
    port: 8983
    log_level: WARNING
    path: /solr/staging
