production:
  solr:
    hostname: localhost # NOTE: We use SOLR_URL
    port: 8983
    log_level: WARNING
    path: /solr/production
    # read_timeout: 2
    # open_timeout: 0.5

development:
  solr:
    hostname: search
    port: 8983
    log_level: INFO
    path: /solr/development

test:
  solr:
    hostname: search
    port: 8983
    log_level: WARNING
    path: /solr/test

staging:
  solr:
    hostname: localhost # NOTE: We use SOLR_URL
    port: 8983
    log_level: WARNING
    path: /solr/staging
